### ISSUE TITLE
Codebase audit: managing mutations 

### ISSUE THREAD

**Issue by mps114** [onaio/gisida#175]
Will leave comments here with line numbers

**Comment by mps114** [comment]
Keeping track of the files I have looked at and where there may be mutations. https://docs.google.com/document/d/1v1JcaV07F2AUBlZ0bW8OmLVw5z7ZUPguYPUrMIJZflE/edit?usp=sharing

**Comment by cKellyDesign** [comment]
https://docs.google.com/document/d/1pAdFa4wwZ-H_ecTR_f1PAVtL9YayjTljCXZKXlx-lOc/edit?usp=sharing
