### ISSUE TITLE
Research Oauth2 Implementations

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#186]
Find documentation, examples, articles, etc relating to using ONA Oauth2 authentication in Gisida to authorize ONA API calls to fetch files and data.

**Comment by mps114** [comment]
https://docs.google.com/document/d/1_A6aYbsU8jimk9KXqpurWiy3EFV1_Bj5GJcv6mX2poM/edit?usp=sharing

**Comment by KipSigei** [comment]
What do you guys think about using JSON web tokens for authentication, maybe with the Auth0 authorization framework?

http://jasonwatmore.com/post/2017/12/07/react-redux-jwt-authentication-tutorial-example

**Comment by cKellyDesign** [comment]
I think Dickson suggested staying away from using webtokens and to use Oauth2 (#34)

**Comment by cKellyDesign** [comment]
**Basics**
* https://auth0.com/docs/protocols/oauth2
* https://auth0.com/blog/oauth2-the-complete-guide/

**Oauth2 Grant/Flow Types**
* https://medium.com/@robert.broeckelmann/when-to-use-which-oauth2-grants-and-oidc-flows-ec6a5c00d864
* https://labs.hybris.com/2012/06/05/oauth2-the-implicit-flow-aka-as-the-client-side-flow/

**Third Party Modules**
* https://github.com/lelylan/simple-oauth2
* https://github.com/andreassolberg/jso
* https://github.com/mulesoft/js-client-oauth2
