### ISSUE TITLE
Research Canopy CSV to Gisida Simple Connection

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#187]
As a Canopy Client I want to be able to use the Superset Slice CSV or JSON output as a Gisida layer source.

This ticket tracks research outcomes, insights, and conversations.

**Comment by cKellyDesign** [comment]
**CSV Output URL**
https://superset.ona.io/superset/explore_json/?form_data=%7B%22slice_id%22%3A[SLICE_ID]%7D&csv=true

**JSON Output URL**
https://superset.ona.io/superset/explore_json/?form_data=%7B%22slice_id%22%3A[SLICE_ID]%7D

Using either of the outputs above fail for the following reasons:
1. Gisida looks for the file extension to determine CSV from JSON (this is an easy fix)
2. The dataset itself requires authentication (which Gisida is not providing) so the slice and its output get access denied.

As discussed in the gisida slack channel, we can't just make the dataset public otherwise it would show up in all clients' list of datasets. Also we need to be able to handle private data for most of our clients.

**Next Steps**
1. Short term: none
2. Longer term: authenticate users with ONA and/or Canopy credentials and build a Canopy CSV/JSON slice connector into Gisida

**Comment by csc5k** [comment]
An alternative to 2) would be setting up a Superset instance per client, and then labeling those dataosurces as "public" (so they can be accessed without credentials). I suspect this is not desirable as the overhead of managing many Superset instances could be quite heavy.

I agree with Conor's notes that 2) is the way to go - find a way to pass credentials to Canopy so that we can use these URLs to return CSV / JSON data to Gisida.

**Comment by engwiri** [comment]
I dont think exposing our client data in any way is how we want to pursue this. We definitely should try and see if we can get funding to explore the authentication route. If we get the GRP project this is something we have to do anyway

**Comment by cKellyDesign** [comment]
The common denominator here seems to be authentication, which so happens to already be on Gisida team's plate. It seems like Canopy-Gisida connection is essentially blocked by the lack of authentication method.
