### ISSUE TITLE
Notification when Forms change and break Map layers and/or Dashboard components

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#192]
As a Gisida client with live layers linked to ONA forms, I should be able to understand how changes to the form will effect the Gisida maps and dashboards.

Currently clients may be aware that some layers are driven by form data, but without looking through the XLSForm and the layer/summary configs it is virtually impossible to know which form fields effect which layers / infographics.

**Proposed Solution**
If we render the effected/broken view with some form of notification, form editors will learn the correlation between form fields and map layers / dashboard components.

@csc5k @engwiri - Thoughts on prioritization for this? I'm not sure if it's actually in scope but we could probably sell it as an HCD improvement.

(aka - "We have noticed this pain point and have a solution for some 💵💸💰!")

**Comment by cKellyDesign** [comment]
### Dashboard
In this case, client changes to the C4D form in ONA has broken metric and sector the progress indicators because the calculate fields used for indicator sum totals were either renamed or removed. 

Fortunately we have an `description` field in the summary.json configuration which can be used to display a warning in the case of missing / `NaN` data (aka - an Indicator sum/total)

**To Do**
1. Detect all `NaN` and populate list of corresponding form IDs and Fields
2. Overridew Indicator / Sector description property (with form ID and effected Fields)
3. Change icon class of info button from `i` to `!`
4. Hover / Click shows description popup with warning
    a) "Something seems wrong here... Check form [Form ID] for the following fields:"
    b) `<ul>` list of effected Form Fields
    c) Link to ONA.io in a new tab

**Level of Effort**
~1 day

**Comment by engwiri** [comment]
I think this would be great to implement but I highly suspect it would be out of scope. If the new contract is approved, I think we should implement it but its not an immediate priority for me at this time.

**Comment by cKellyDesign** [comment]
Wonderful, that's kinda what I thought too :)
