### ISSUE TITLE
ONA Oauth Connector Module

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#193]
Authorization/Authentication and resources will be mitigated through a connector module specifically for the ONA API. This module can include authentication wrappers for existing ONA Connector calls to the API as well as utilities for encryption if necessary.

**Comment by cKellyDesign** [comment]
### Next Steps
- [ ] Add Routes and Actions for an Oauth2 Implicit Grant Access (like Canopy-Flow)
- [ ] Update Existing connector to use `fetch()`
- [ ] Make this all optional and extensible!

**Comment by cKellyDesign** [comment]
@pld @ukanga @KipSigei @ivermac 

I am almost finished implementing the supplemental authorization/authentication method we spoke about previously, where we use a config file (in the place of a user service/datastore) uploaded to an [ONA form](https://ona.io/onahelp/37394/310740). **However, I am now running into an issue retrieving this config file through the API.**
### The Issue
1) The [forms API endpoint](https://api.ona.io/api/v1/forms/337143) reveals the `auth.csv` config file `pk`
2) The [metadata API endpoint](https://api.ona.io/api/v1/metadata/1267176) returns information on the correct file and reveals the S3 resource URL
3) The S3 resource cannot be accessed via JS `fetch()` due to cross-origins issues
4) The [media endpoint](https://api.ona.io/api/v1/media/1267176) returns an image from a different form and not `auth.csv`
5) The [files API endpoint](https://api.ona.io/api/v1/files/1267176) returns `Not Found`.

### An Alternative Option
Instead of uploading an `auth.csv` config file, we can create a simple new Auth Form with submissions for each User and their access rights to different Views and Layers. Then these submissions could be retrieved via the `data` API endpoint without cross-origin issues.

How does this approach sound to you guys?

(FYI - This is the last step before we have a complete Oauth2 flow for Private React Views!)

**Comment by pld** [comment]
Hmm, I think that approach sounds fine to me, with the caveat that we may
want to tweak it in the future.

@ukanga?

**Comment by cKellyDesign** [comment]
Agreed, this could be good as a work-around for this first iteration. :)

**Comment by cKellyDesign** [comment]
**Updated Specs**

![gisida auth spec v1b](https://user-images.githubusercontent.com/4141527/45185444-0f75c580-b1df-11e8-82a4-116e6591baa0.jpg)
![gisida auth user journeys v1b](https://user-images.githubusercontent.com/4141527/45185446-1270b600-b1df-11e8-853d-838e8b7dd87c.jpg)

**Comment by ukanga** [comment]
> 2. The metadata API endpoint returns information on the correct file and reveals the S3 resource URL

I would probably suggest you append the file format on the metadata endpoint, for example, https://api.ona.io/api/v1/metadata/1267176.csv works without redirecting to S3 links.

> 3. The S3 resource cannot be accessed via JS fetch() due to cross-origins issues

Probably we may need to configure CORS for our bucket as described at https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors. We may need to do it on the Ona API side as well if we haven't added your domain.

Be aware that S3 links expire, so if they are used at the time you have made the request then you should be good.

> 4. The media endpoint returns an image from a different form and not auth.csv

There is no relation between media endpoint and metadata endpoint, the media endpoint is for submission attachments hence the different image.

> 5. The files API endpoint returns Not Found.

The files endpoint is also about submission attachments and not metadata.

**Comment by cKellyDesign** [comment]
Oh interesting, I will try using the .csv extension to fetch the resource directly through through the metadata endpoint.

Using the data endpoint to grab form data tends to work really well actually, is there a reason why we should **not** be using an ONA form submissions as a v1 user store/service?

**Comment by ukanga** [comment]
I believe there is no reason for you using submissions to a form. I think when we discussed the form represented a dataset or project and media files represented the supporting files for this dataset or project.

**Comment by cKellyDesign** [comment]
You're right, the only reason it works well is because the host `localhost:8080` is whitelisted so it doesn't run into CORS issues. We'll change this connector to use the `.csv` file extension as mentioned above and get the Supplementary Auth config being ingested from the form attachments.

**Comment by cKellyDesign** [comment]
Closing this as Gisida should manage user auth via Gatekeeper.
