### ISSUE TITLE
Sync Public Som Nutrition Website with Service Mapping

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#196]

**Comment by KipSigei** [comment]
The codebase has been updated via https://github.com/onaio/nutrition-cluster/commit/e07e5fe03d8786ea975f47958756e3bee50dfb1c , data work is still remaining

**Comment by dkwamboka** [comment]
Changes to be made are contained in this: [sheet](https://docs.google.com/spreadsheets/d/1Q738y2YekeENl0JVe22dauYh2lSTT1HWPCMJ8Sm7nr4/edit?usp=sharing).
