### ISSUE TITLE
Add Router to Support Oauth2 Flow

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#199]
The Oauth2 Flow requires a `/callback` endpoint to receive credentials after Authorization. Even a simple router can also help us manage Access Privileges of Views and Layers and drive Authentication.

**Comment by csc5k** [comment]
Next steps:
- PRs need to be reviewed
- Release 1.1 of Gisida and Gisida REACT

**Comment by cKellyDesign** [comment]
- [ ] Merge `signin-auth-dev` into staging

**Comment by cKellyDesign** [comment]
This should have closed with onaio/gisida-react#148
