### ISSUE TITLE
Update Padding Between Last Facility Layer and Next Layer

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#210]
We need to update the padding between the last facility layer and the "Number of Women who Received HIV Testing and Counselling" menu so that it is better.

**Comment by cKellyDesign** [comment]
This is done (https://github.com/onaio/gisida-react/commit/45279e04f1b00c540d591d5e10646594a24e16bf), it just needs to be deployed so we'll send it up with other bug fixes!
