### ISSUE TITLE
Investigate Data Discrepancy in Layer

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#212]
The legend for the layer "Children (0-11 months) who received penta3 vaccine at facility" goes up to ~9256 but the largest circle only goes to ~8287 (these numbers are as of last week, so may be different now)

We need to investigate the discrepancy

**Comment by samwata** [comment]
@csc5k I have gone through data and noticed that the Geolocation for these two Health facilities were not provided in the geolocation list that were provided earlier 

cxb_municipality | Cox's Bazar Municipality Health Office
-- | --
chakaria_uhc | Chakaria Upazila Health Complex

**Comment by csc5k** [comment]
Cool, thanks. Let me check with them

**Comment by csc5k** [comment]
The full list is here: ![image.png](https://images.zenhubusercontent.com/5b51ec168c1a7628d9218a4b/5798410e-2ac6-4cc4-ac2b-55febece90db)

**Comment by samwata** [comment]
Thanks @csc5k I will add this points
