### ISSUE TITLE
Layer Displays No Data but Legend Has Data

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#215]
The layer [HC - children under five attended for healthcare] does not display data on the map but does display data in the legend. This is true for all points in the timeseries slider.

We also need to adjust the labelling so the date ranges fit better in the slider box at the top right of the window.

![image.png](https://images.zenhubusercontent.com/5b51ec168c1a7628d9218a4b/edc181ed-2c69-47d9-9c6f-529cd7959b2c)

**Comment by KipSigei** [comment]
fixed in https://github.com/onaio/rohingya/commit/960fbeb6d2a931b48aa040cb246b14d21ce8936a and https://github.com/onaio/gisida-react/commit/dae019b358f9ab367123cc239b691b2220ce4ccb
