### ISSUE TITLE
Get Shape Files from DHIS API

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#220]

**Comment by cKellyDesign** [comment]
@csc5k @engwiri - In the kickoff meeting the other day we mentioned that the DHS API can return geometric data to use for shapefiles...but this could be problematic.

**1) Heavy GeoJSON** - If we download data with geometry, the two are in a single heavy file where we want these data decoupled to keep both files light (data without geometry & geometry without data)
**2) Country Level GeoJSON** - The geometry endpoint will only return geojson broken down by subnational shapes (for some reason I cannot get the country boundaries to work correctly)
**3) Missing Regions** - The subnational geometry being returned is only for regions which actually have data (so with Kenya there are several spots without geometry over the years). I'm sure we could visually handle this with a design solution, but the raw data is just not there.

Thoughts?

**Comment by engwiri** [comment]
@cKellyDesign yeah I agree but I do think this is a phase 2 problem i.e. we are not required to pull any data using the API for this first phase although its a good idea to explore so we know what we are promising.

To answer your questions:

1) Heavy  GeoJSON - We only need to download geometry once - I hope! so we should probably decouple it if we can.
2) We can get country level shapes from elsewhere doesn't need to be from the geojson string. I assume they also did not have country level data (its aggregated from the data) so they don't need to have country level boundaries.
3) This is fine, if we know what level they are - counties or districts we can get the full list from elsewhere and just match the data to the ones that apply

I hope this answers your questions.

**Comment by cKellyDesign** [comment]
@engwiri - that makes sense for the most part, except we need to deal with this somewhat for phase 1 since we need the geometry to render the map (obvi) and we need to show the geometries updating over time. I do agree that Gisida should not be pulling anything from the API in this phase, just that we need to get these updating geometries from somewhere (and it seems like the API should be the primary source of subnational admin boundaries).

1. Yeah I think we'll have the geometries saved in a single large mapbox tileset, decoupled from the actual data.
2. True, we can get these from other sources, we just have to be mindful of national level admin boundaries that also change over time.
3. It may actually make sense to leave these missing counties or districts out of the sub-national renderings since they represent areas which were not surveyed at those times.

For now I can compile a collection of geoJSON files representing the admin boundaries at the different time periods to try and get us started :)

**Comment by cKellyDesign** [comment]
@Janemesi @dkwamboka - We were able to figure out how to fix the invalid geometries from DHS and merge the Admin_1 features into an Admin_0 geometry! [The documentation](https://docs.google.com/document/d/11gqsO_zoM57gyMDIZpsTGh3qaLSQrX5I3LrWxj77KKY/edit#heading=h.u82nf0hovhq1) for this step is updated and a bit simpler now.

**Comment by cKellyDesign** [comment]
I've pushed the json files used to create the new tileset to the esaro repo (onaio/esaro#3), and as usual it looks like there are a couple things going on.

One thing is the `endYear` attributes in the geojson for the last available year in a country, this value should be something in the future to allow it to show for future time periods. I had arbitrarily chosen 2050 (but we could also use 3000 or `Infinity`) with the idea that this property of the geojson features would be updated if new admin boundaries were added. This should be a pretty simple fix!

![screen shot 2018-11-09 at 12 23 33 pm](https://user-images.githubusercontent.com/4141527/48278950-11e1df00-e41d-11e8-9af0-545abed59191.png)

**Comment by cKellyDesign** [comment]
Another issue the fact that some of the [DHS data](https://api.dhsprogram.com/rest/dhs/data/KE,2014,ED_NARS_B_GPI?f=html&breakdown=subnational) is returned [broken down by old Admin boundaries](https://github.com/onaio/esaro/blob/ecelayer/public/data/school_participation_subnational.csv#L103-L110), despite returning [new admin geometries](https://github.com/onaio/esaro/blob/ecelayer/lib/geojson/KE/1/KE_2014_1.min.geojson) for the same year. **This is likely why their geometries contain BOTH / ALL sets of geometries.** (....:man_facepalming:)

Probably the easiest path from this point until Tuesday, will be to keep using the original Tileset and simple prune any CSV rows which would cause geometries to visibly overlap when filled. We might also have to append or prefix persisting old geometries IDs since some share IDs with newer geometries.


_Pro Tip - Inspect map features you are clicking on by opening your browser's Console and running:_
```
window.maps[0].on('click', (e) => { console.log(window.maps[0].queryRenderedFeatures(e.point)) })
```
_Clicking on the map will then return a list in the Console of all features under the point of click!_

**Comment by cKellyDesign** [comment]
@csc5k - It looks like the bugs you pointed out (where countries suddenly stop rendering) is also due to the original tileset having incorrect `endYear` values. In this case the `endYear` should be 2016 (year of the next updated geometry).

![screen shot 2018-11-09 at 3 55 35 pm](https://user-images.githubusercontent.com/4141527/48287892-6777b500-e438-11e8-85e9-c360ddf167e9.png)

**Comment by cKellyDesign** [comment]
This issue was moved to onaio/esaro#5
