### ISSUE TITLE
Investigate why API returns 404 status when making requests with an expired OAuth2 token

### ISSUE THREAD

**Issue by KipSigei** [onaio/gisida#226]
Find a way on how we can support OAuth2 token refreshing with the implicit grant flow when the token expires and check why the API returns a 404 instead of a 401.

**Comment by pld** [comment]
What's the specific endpoint? I think this is appropriate for some endpoints, the idea here is that we leak information if a user can ping different endpoints and gets a 404 for one's that don't exist and a 401 for others that do. If we did that someone could scan us to figure out what usernames exist.

I also think there are other endpoints that will return a 401. Here's some milia code that handles refresh of expired tokens (but in a different way since it goes to the zebra backend and it's using basic auth temp tokens not oauth), https://github.com/onaio/milia/blob/master/src/milia/api/io.clj

**Comment by KipSigei** [comment]
This seems to be happening on the data and the forms endpoints, the user endpoint returns a 401.

Apparently, implicit grant flow doesn't support token refresh as seen in this doc https://oauth2.thephpleague.com/authorization-server/implicit-grant/ , which means we might have to resort to using the API's `temp_token` from the user profile

**Comment by pld** [comment]
Let's try to avoid the temp_token. Can we use a different type of grant?

If not, and even if so, for now we can gracefully log-out the user on expiration and come back to this later.

If we get a 404 on an endpoint we expect to not, we can hit the user endpoint and if that gives a 401 return a message saying their session expired and send them to the login flow.

Certainly not good long-term, longer-term we would replace the message and redirect with refresh logic.

How does that sound?

**Comment by cKellyDesign** [comment]
I don't think we want to switch up the grant access type, the implicit flow is the standard approach for such front end SPAs.

I think a graceful logout is the best approach here, especially for starters. 

Peter and I chatted a little bit about this the other day, but I'm curious: what is the use-case for refreshing the token without making the user sign back in? Don't tokens last for 6 hours or something like that?

**Comment by KipSigei** [comment]
As a temporary solution, @ukanga suggested that when we first authenticate with the provider, we get the `expires_in` value and store  in a cookie/localstorage then essentially check if the token is still valid with every request to the API,  if it has expired and the API returns a 404 then we log out the user to allow them to log in again and get a new oauth2 token.

**Comment by pld** [comment]
The use-case for the refresh is so that they don't have to log back in
again, I'm sure we will want that in the future. Vast majority of web-apps
don't auto-logout after an expire period

**Comment by cKellyDesign** [comment]
Right, I guess most don't auto-logout, but a certain class of sites (like banks, healthcare systems, etc) will either auto-logout or prompt the user to extend their session. In these cases the information is extremely sensitive (though arguably not more sensitive than FB or G-Suite) and our client data is probably not on that same level. Cool, I'm on board! :)

**Comment by cKellyDesign** [comment]
Closing this b/c we need to manage user Auth state with Gatekeeper.
