### ISSUE TITLE
Add Filter to Mapping Website to Disaggregate by Upazila

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#238]
We should add a filter to the mapping website to disaggregate by upazila

**Comment by cKellyDesign** [comment]
This should simply require adding an `Admin_3` and/or `Admin_3_Label` column to [local site data CSV](https://github.com/onaio/rohingya/blob/phase-2/public/data/180320_Outline_Rohingya_refugee_camps_sites_centroids.csv) and added to the layers as [another filter option](https://github.com/onaio/rohingya/blob/phase-2/public/config/layers/PLW-hiv-testing.json#L55-L58).

**Comment by cKellyDesign** [comment]
@csc5k Do we need to have `Upzila` map layers?

**Comment by csc5k** [comment]
I don't think so. Let me confirm

**Comment by KipSigei** [comment]
@cKellyDesign i think i saw an upazila column in the join CSV

**Comment by cKellyDesign** [comment]
That would be sweet if we already have it in there, but easy to add if it's not!
