### ISSUE TITLE
Facilities Layer Shows No Data and Has No Date Slider

### ISSUE THREAD

**Issue by csc5k** [onaio/gisida#241]
The health facilities layer shows no data and does not have a date slider. This should show the facility locations and show how they move over time 

![image.png](https://images.zenhubusercontent.com/5b51ec168c1a7628d9218a4b/4bae385e-f1e3-4fd2-8ecf-a64ec580f6f6)

**Comment by cKellyDesign** [comment]
@csc5k Do we have different data for this now? Otherwise this seems like onaio/rohingya#45 which is blocked by data being to disparate to come together (if my memory serves...).

**Comment by samwata** [comment]
@csc5k @cKellyDesign This layer was created to show all facility centers that were provided using a green triangle icon.

**Comment by cKellyDesign** [comment]
Ah ok I will take a closer look :)

**Comment by cKellyDesign** [comment]
1. The `Health_facilty_govt-76jize` [mapbox tileset](https://www.mapbox.com/studio/tilesets/ona.du1e5n79/) has a maxZoom of 10 so currently this tileset will not render when zoomed in so far. We easily can get around this with Mapbox's tippecanoe command-line to manually set the zoom levels.
2. Nothing is rendering when zoomed out (within the zoom bounds of the tileset), so I'm still investigating why.

@samwata - Do you know the source for this [tileset](https://www.mapbox.com/studio/tilesets/ona.du1e5n79/)?

**Comment by samwata** [comment]
@cKellyDesign Yes am the one who created the tileset I will send the source geojson file on rohingya channel
