### ISSUE TITLE
[Filters] Add cross-filter OR functionality

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#28]
Example - Facilities funded by World Vision OR facilities in a certain region.

**Comment by cKellyDesign** [comment]
We discussed the issue of toggling AND/OR functionality across top level filters via a toggle button next to the global filter search icon. Kip gave a great example earlier on what the difference between AND and OR functionality results in:

```
/* AND Filter - filters down to an intersection of the selected parameters */
admin-params = { country: KE, region: Central }
admin-results = [{Central Kenya}]

/* OR Filter - filters down to a union of the selected parameters */
admin-params = { country: KE, region: Central }
admin-results = [{<all regions> Kenya}, ..., {Central Uganda}, {Central <any other country with central>},...]
```

I'm seeing some OK icon options in [glyphicons](https://glyphicons.bootstrapcheatsheets.com/) (but not great), and thought we could try something with overlapping shapes (like union/intersection tool icons):

![crossfiltertoggle_3x](https://user-images.githubusercontent.com/4141527/49168880-7f8b7780-f306-11e8-9f49-92fc6fb85ba8.jpg)
![crossfiltertoggle](https://user-images.githubusercontent.com/4141527/49168989-c24d4f80-f306-11e8-9b54-4b938661c0f5.png)

Or we could use something else, either way then we could just have button element `alt` tag handle the tooltip to explain what the button does.

**Comment by cKellyDesign** [comment]
Other small things:
- [ ] Filter Component should use layerObj with filtered source.data for timeseries
- [ ] Checkboxes should not de-select across filters
- [ ] Gap filling data should be de-duplicated across time periods (pic below)
<img width="1272" alt="screen shot 2018-11-28 at 5 00 38 pm" src="https://user-images.githubusercontent.com/4141527/49185659-72837e00-f330-11e8-98ca-b37e7a8b0152.png">

@KipSigei - Does this sound right?

**Comment by KipSigei** [comment]
@cKellyDesign yes

**Comment by cKellyDesign** [comment]
Looks like the cross-filtering toggle functionality is working really well, good job hooking it up and getting it working first! In terms of this button:

- [ ] Convert slide toggle to a button using AND / OR icons
- [ ] Toggle button should have Alt text displaying the AND / OR cross-filtering state
- [ ] Update (or clear) the selected filters options when toggling between AND / OR cross-filtering state
