### ISSUE TITLE
Data values not matching limits defined in layer spec

### ISSUE THREAD

**Issue by KipSigei** [onaio/gisida#288]
For layer categories without breaks, when generating stops some data values tend to fall into clusters or data groups that are outside their specified limits

**Comment by muneneg** [comment]
As shown in the screen grab;
![image](https://user-images.githubusercontent.com/41571129/58616231-d2e67e80-82c5-11e9-970c-39a1c0da53e9.png)
Values 15,22,27 are all under the group `0-30`, but 15 has a different shade than the others. 22 and 27 pick the shade of `31-60`
