### ISSUE TITLE
Add a functionality to handle geo points through superset connector

### ISSUE THREAD

**Issue by samwata** [onaio/gisida#315]
When you have points in superset and you want to show these points on the map, you get this error. 
![image](https://user-images.githubusercontent.com/23456184/61039133-e0b81500-a3d6-11e9-8d73-c5a541c1ab06.png)

Add a functionality that will handle points(latitude and longitude) through superset connector

**Comment by moshthepitt** [comment]
@samwata this is something that we are able to do in reveal i.e. get points from Superset for Gisida (inside reveal) to display on a map.

Can you share the slice/chart in question?  We may need to tweak it so that it outputs something that Gisida can more easily take in.

**Comment by samwata** [comment]
@moshthepitt  I want to display points in this [table](https://discover.ona.io/superset/explore/?form_data=%7B%22datasource%22%3A%22389__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A812%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3Anull%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22100+years+ago+%3A+%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A1000%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%22group_pelapor_puskesmas%22%2C%22group_pelapor_puskesmascode%22%2C%22day%22%2C%22latitude%22%2C%22longitude%22%2C%22month%22%2C%22group_pelapor_provinsi%22%2C%22group_pelapor_kabupaten%22%2C%22province%22%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%7D) on Gisida.

**Comment by cKellyDesign** [comment]
Kip mentioned this in our standup this morning, it should be a pretty light lift, we just have to tell gisida to use the same functionality as CSV layers to generate the geojson points from the long/lat columns.

@KipSigei - think we'll want to bump gisida's version for this so we can update it / use this functionality in Reveal
