### ISSUE TITLE
Add the cyclone path layer to Fiji NDMO site

### ISSUE THREAD

**Issue by msschroeder** [onaio/gisida#361]
- [ ] Please add another tab "Nature Data" to the Fiji NDMO GISIDA site (https://ndmo-fiji.onalabs.org/)
- [ ] Under this tab, please add the cyclone path data, called "Cyclone Sarai - Route"

Shape files can be found will be shared in DM

**Comment by kahummer** [comment]
@msschroeder Do we have a go-ahead from the client to use this geometry?



<img width="354" alt="image002" src="https://user-images.githubusercontent.com/16018123/72993647-cbe91f00-3e06-11ea-8ee1-709980a1d29a.png">

**Comment by msschroeder** [comment]
@kahummer Yes, this is okay.
