### ISSUE TITLE
Hide menu groups without accessible layers

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/gisida#367]
If a user does not have access to any layers in a menu group then that group menu item should be hidden to make it inaccessible, if a section has no accessible groups then that section should also be hidden.

- [x] Hide menu groups / sub-groups if there are no accessible layers
- [x] Hide menu sections if no accessible groups
- [x] Deploy updated bundles to Mesh2

**Comment by kelvin-muchiri** [comment]
This is done https://beta-dppsomalia.onalabs.org/. Waiting for a PR review so that the changes can be incorporated into other projects.

**Comment by cKellyDesign** [comment]
@kelvin-muchiri can this be closed?
