### ISSUE TITLE
Create a GISIDA site for UNICEF Pacific for SPA for Vanuatu

### ISSUE THREAD

**Issue by msschroeder** [onaio/gisida#370]
Requestor: Megan - UNICEF Pacific - SPA

Description
We need to set up a new GISIDA site for a client. 
- [x] Create a GISIDA site for Vanuatu - Pacific Islands using a basemap from MapBox
- [x] Use the domain name: spa-vanuatu.onalabs.org
- [x] No password required at this time - this may be added later - is that a problem?

Create the following layers:
- [x] Header label "Boundaries and Labels"
- [x] Under "Boundaries and Layers", Please add a layer for "Province Boundaries"
- [x] Under "Boundaries and Layers", Please add a layer for "Province Labels"
- [x] Under "Boundaries and Layers", Please add a layer for "Area Council Boundaries"
- [x] Under "Boundaries and Layers", Please add a layer for "Area Council Labels"

NOTE: Eventually, we may want to add a Canopy Dashboard to the GISIDA site (not sure if that is helpful information)

Shapefiles:
https://data.humdata.org/dataset/vanuatu-administrative-level-0-1-and-2-boundaries

Dependencies
No dependencies

Priority
7-8

Timeline
Feb 1st - There is not a huge rush. But it would be nice to get going

**Comment by kelvin-muchiri** [comment]
Could we have an idea (description) of what the dashboard is about? Would help in defining a nice description when setting up the client repo

**Comment by kelvin-muchiri** [comment]
@msschroeder This is done

**Comment by cKellyDesign** [comment]
This is waiting for client sign-off

**Comment by kelvin-muchiri** [comment]
Here is the link http://spa-vanuatu.onalabs.org/

**Comment by msschroeder** [comment]
Quick one - Is it easier to add a password now or later? Because right now - one is not needed, but probably will be needed later

**Comment by kelvin-muchiri** [comment]
Sure, we can add it
