### ISSUE TITLE
Zimbabwe Idai Recovery site updates 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#396]
We need the following updates made to the infrastructure site 
https://drive.google.com/drive/u/0/folders/1V4pzuN0GaR3BgmKFP9wdynPWqOsu8lG-

The maps can be found in the link above. The name to categorise this should be *_Public infrastructure *_

@ciremusyoka has already made updates to one of the documents. 
Note If the points within the files do not have any data you can go ahead and filter data 

Turn off the following layers 

* [x] Health 
* [x] Education 
* [x] Nutrition 
* [x] Wash

**Comment by akahure** [comment]
Updates/ Comments 

- [ ] Include filters for all the points  inclusive of water points 
- [ ] Colour based on function - water points blue, anything that is not clear make sure it appears darker 
- [ ] Remove of the roads layer  from the Settlement + Services 
- [ ] Water points size its too small - need to be viewed when loaded 
- [ ] Change wash in the severity needs title to 'WASH' - capital in severity needs

**Comment by ciremusyoka** [comment]
@Janemesi  for layers which require filters and are pulling data direct from mapbox have to be changed.

**Comment by cKellyDesign** [comment]
@ciremusyoka @Janemesi @akahure @kahummer Can this be closed?
