### ISSUE TITLE
Zimbabwe Idai - Better visualisation icons for the site 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#423]
In the Zimbabwe Idai Recovery site we currently have icons for the infrastructure layers already built into the site. 

When you click on a layer, the icons appear on the site as shown in a couple of the screenshots below 

![Screenshot - 2020-02-11T155329 834](https://user-images.githubusercontent.com/43808025/74238371-b3be3e80-4ce6-11ea-87e7-4c3086d233ed.png)

The client has expressed that we should have a better way to show these icons and also include a legend for them. The request here is to have mockup icons for the following sites, that can be used to be more descriptive to the user and included in the site. 

To access the site icons, navigate to 
https://idairecovery-zimbabwe.onalabs.org/
username:idaipublic
password:public 

![Screenshot - 2020-02-11T155204 499](https://user-images.githubusercontent.com/43808025/74238270-82de0980-4ce6-11ea-9484-653c9ac5a5d9.png)

**Comment by cKellyDesign** [comment]
@akahure what icons do they want? Do we need to bring @rowo into this conversation?

**Comment by akahure** [comment]
@cKellyDesign the idea is to relook at the icons we have for the public layer and check if the icons we are using here portray what is intended by the specific layers. The thing is the client is not clear on what icons would aid in presenting more information, sorry its vague, maybe we review the current icons and make some suggestions on possible improvements. Open to have a quick meeting

**Comment by mberg** [comment]
please look at noun project and make suggestions. which icons are they not
happy with?

**Comment by akahure** [comment]
They are not pleased with the bridges and sanitation, as shown below
![Screenshot - 2020-02-12T101901 923](https://user-images.githubusercontent.com/43808025/74311724-22e87100-4d81-11ea-8d96-cff5fb2e28d0.png)
![Screenshot - 2020-02-12T101835 028](https://user-images.githubusercontent.com/43808025/74311728-25e36180-4d81-11ea-8f2e-4cf853478169.png)

Perhaps we can use the below icons for the two, but will check on any recommendations they have, as mentioned we can include a legend as well, that should provide more context for the icons which could be what they need. 
![images](https://user-images.githubusercontent.com/43808025/74312045-e8330880-4d81-11ea-8d5d-626cf34d35d1.png)

**Comment by rowo** [comment]
@akahure @mberg Please use the UNOCHA humanitarian icons where possible. I think it's good to push that standard and not use random stuff.
Here's sanitation: https://thenounproject.com/search/?q=sanitation&collection=62718&i=2013954
Here's a few bridges: https://thenounproject.com/search/?q=bridge&collection=62718

**Comment by cKellyDesign** [comment]
@kahummer what's the status of this deliverable?
