### ISSUE TITLE
heatmaps for UNOPS idai need a subtle view of the heat map

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#425]
In UNOPS IDAi we currently have a couple of heat map layers done and need a way to see if we can present these layers better, without 

Showing the layers with breakdown to indicate urgency such as with the screenshot below and this should not be the idea 

![Screenshot from 2020-02-11 15-44-36](https://user-images.githubusercontent.com/43808025/74239398-d3566680-4ce8-11ea-8a12-c79e4713015c.png)

_Reference from the client "The colour scheme used on the heat map legend is quite misleading, as one can interpret it as 'wash point' is the most severely affected sector. For improvement, I suggest the use of more subtle/lighter colours for the legend. "_

**Comment by cKellyDesign** [comment]
@akahure it's not clear to me what is being requested from this ticket. Showing multiple heatmaps at one time is intrinsically problematic, which is why we used different colors for different heatmaps, because they are categorical.

> For improvement, I suggest the use of more subtle/lighter colours for the legend.

Using lighter colors will only make it harder to read / understand what is going on. Maybe we could reduce the `heatmap-radius` property to make them less blotchy and to overlap less, but that is a process that takes a lot of tweaking and will need to be done on a layer by layer basis.

**Comment by cKellyDesign** [comment]
@akahure - This color scheme is @kahummer's attempt to satisfy the request, I think it definitely addresses the fact that the red looked like it was "worse" than the other areas. Not sure if there's much more we can do to improve the readability of the compound heatmaps.

![Screenshot from 2020-02-11 17-46-19](https://user-images.githubusercontent.com/4141527/74249651-5b634e80-4c9e-11ea-971a-fe75df3a9d18.png)

**Comment by mberg** [comment]
Why are we trying to do compound heatmaps?  I'm not sure it's a good idea

**Comment by cKellyDesign** [comment]
@mberg i believe it was being explicitly asked for by the client and using multiple heatmaps is the only way to show the different categories.

**Comment by cKellyDesign** [comment]
@akahure i would also say that our method of overlaying semi-transparent heatmaps is working, in this screenshot the darker spots are where there is the most overlap:

<img width="872" alt="Screen Shot 2020-02-11 at 11 10 01 AM" src="https://user-images.githubusercontent.com/4141527/74269957-392df880-4cbf-11ea-87ee-34c027be53fd.png">

**Comment by akahure** [comment]
This is what the client was asking for, I think this looks a whole lot better from a presentation point of view. Can we move the Damages to go above the SNI index ? @kahama94
