### ISSUE TITLE
Create a summary convergence layer on Spotlight (discussion )

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#429]
The visualisation requested, should have the convergence build viewed on some sort of 'Summary Convergence' . The tone would be based on intensity (colour) on the number of partners represented in a district/ province. 

One idea on how we can do this is

- Leave the current layers that have already been built out (to flag specific pillars)
- Build one 'Convergence layer' that will showcase, a summary possibly by an intensity colour to showcase where partner concentration is. 
- When the mouse is hovered, show a popup with the pillars (in that district or province) and the instances for the partners, something like what we have on UNOPS IDAI Recovery 

Popup showing categorisation 

<img width="1128" alt="Screenshot 2020-02-17 at 13 42 19" src="https://user-images.githubusercontent.com/43808025/74646718-6aa93700-518b-11ea-901d-f19334fe9279.png">

The tricky part will be showing count intensity by partner and the further breakdown by pillar.  I presume some sort of summary popup to show the summary on hover

**Comment by cKellyDesign** [comment]
@akahure what's the status / prioritization / assignment of this request?

**Comment by akahure** [comment]
Yeah we can close this and open up the discussion once the client has had a review
