### ISSUE TITLE
Updates needed for UGATlas site 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#436]
- [x] For the health facilities use different icons to differentiate them - like we have for the water points, we should not use intense colours to show since this depicts intensity 
- [x] DHS Health sites - Once a site is clicked, and the filter loads, can we have a tooltip to show that it exists ? or open the filter to show options - on click 
- [x] Once the health sites are opened, and a user opens one, the popup that opens shows a profile view. The client would rather have the detail appear in the popup and not profile view 
- [x] Water points -  It needs to be visualised in the same way as all point data. Please see the first item (Point data needs to be clustered at higher levels and then de-clustered as you zoom in more) e.g.https://www.arcgis.com/apps/Cascade/index.html?appid=4eff1f0e80344639b918cbd99b8523ff
- [x] Water points - we need more subtle colours to represent the points, no use of red or green it paints a picture of severity/ functionality (also check in the file we have, if we have functionality listed)
- [x] Education facilities - Clustered at high level and then zoom in to show the point data 
- [x] Refugee Population - In addition to the popup we need to include the host population (district population)
- [x] Poverty and Household updates - New dataset shared with the household and poverty attributes needs to be uploaded. 
- [x] Poverty and Household updates - Need to update these to include percentages and not just the basic numbers as they are right now 
- [x] Per Capita - In the screenshot attached there is no MC Wage/ non wage view in the sub region level
<img width="547" alt="Screenshot 2020-02-26 at 11 51 10" src="https://user-images.githubusercontent.com/43808025/75328419-0a9f4880-588f-11ea-9ace-d6d40d8f6a40.png">

- [x] Fill layer is buggy - once a user selects a fill layer and consequently selects a circle layer,  the layers are turned off of what has been selected.
<img width="1425" alt="Screenshot 2020-02-26 at 12 03 41" src="https://user-images.githubusercontent.com/43808025/75329057-10495e00-5890-11ea-9edc-7011caaf364e.png">

- [x] Updates to the worship/ religious data set: https://docs.google.com/spreadsheets/d/1rZDkRWoS62Vb3KXKmXaFpuViW_71m6noPQndtw4I1Qc/edit#gid=1790006233
- [x] Updates to Poverty data time slider 2012/2013 and 2016/2017 based on this data set - https://drive.google.com/open?id=1ioaOuqRWGRp5aij8XEc8dAwHcswDM-2B

**Comment by akahure** [comment]
Updates from QA 

- [ ] https://prnt.sc/rax98x the icon in the legend needs to be fixed and the filters need to show the other categories 
- [ ] Consistency with the view of the popup and the data in the profile view 
 <img width="914" alt="Screenshot 2020-03-03 at 17 06 20" src="https://user-images.githubusercontent.com/43808025/75783393-8eff3900-5d71-11ea-8bb9-dab1ee4fdc10.png">

- [ ] Need to add a comma to the code for the population estimates 

<img width="691" alt="Screenshot 2020-03-03 at 17 16 05" src="https://user-images.githubusercontent.com/43808025/75784091-bb678500-5d72-11ea-9e5a-7edbbae1574b.png"> 

- [ ] Add a percentage to legend for the poverty and household rates

<img width="1021" alt="Screenshot 2020-03-03 at 17 19 25" src="https://user-images.githubusercontent.com/43808025/75784431-3af55400-5d73-11ea-91c5-c21b2e0a488b.png">

**Comment by cKellyDesign** [comment]
@samwata @ciremusyoka @akahure - what's the status of these requests? Can this be closed?

**Comment by akahure** [comment]
I need to do QA on this and then close it @cKellyDesign thanks
