### ISSUE TITLE
District and Sub district visualisation - UGAtlas 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#437]
For UGATlas, we need to put together a map coverage visualisation for the Donors and the areas they are operating in. 

We have the master file dataset and can be accessed https://docs.google.com/spreadsheets/d/1UpeVwi4cD3sf_ZMyEf4ceTBvPaH0rWuX/edit#gid=295293688

Below are the tasks outlined
1. Need to join the Geographic sheet with the Donor Sheet into one sheet using _**intCode**_
2. Using this, add two menu drop downs on UgAtlas site to have _District_ and _Subdistrict_ options 
3. Build the layer on UGatlas for the donor coverage such that when a user selects 'District' - a centroid will be loaded to show a popup (on hover) for the partners operating in that district 
4. On click, the profile view will show the name of the district, the donor and the activity area with a financial breakdown 
The same needs to be done for Sub district.

**Comment by akahure** [comment]
@B-Cheye kindly create the file only and we can discuss the implementation. Just had a quick discussion with Erick and we should look at possibly working on the visual based on amount disbursed and not Donors. 
And then in the popup we can show aa summary with the Donor, how many activity areas (count), and amount disbursed per Donor 
I am also checking with the client and we can talk more after I confirm the spec.

**Comment by cKellyDesign** [comment]
@akahure @B-Cheye - UG Atlas work usually takes some engineering support, is that the case here? If not, great! If so can we also assign them to this ticket?

**Comment by akahure** [comment]
@cKellyDesign yes we probably will need some engineering support, but not now. We would like to sign off the scope first before we spend time on implementation.

**Comment by akahure** [comment]
@B-Cheye  @samwata The naming is redundant https://prnt.sc/raxx78
We should use drop down 
- Sub region 
- District 
Also when I click to zoom into a sub region, it should show the breakdown by districts, on click

**Comment by cKellyDesign** [comment]
@akahure @B-Cheye what's the status of this? Can this be closed?
