### ISSUE TITLE
Updates and Fixes requirements needed for Indonesia 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#440]
UNICEF Indonesia 
Bugs - All layers need to be updated 

- [x] Registered facilities - Canopy source (data work)
- [x] Disease surveillance (all layers ) (data work)
- [x] Change health facility Icon https://prnt.sc/rekxeh (data work)

Functionality @kahummer - please check on this 
- [x] We need to include the map split view (engineering)

- [x] Include the map export options (camera icon) (engineering)

- [ ] Would be awesome to center and zoom certain layers for easy visibility (data work)
![Screenshot from 2020-03-12 13-01-28](https://user-images.githubusercontent.com/16018123/76509833-afaa4b80-6461-11ea-945e-534eee323e92.png)

- [x] Filters for the data  (data work)
![Screenshot - 2020-03-11T095738 429](https://user-images.githubusercontent.com/43808025/76390615-c7f56a00-637e-11ea-8163-b32140f52913.png)

- [x] Dashboard check - https://prnt.sc/rekzt3 (data work)

**Comment by cKellyDesign** [comment]
@akahure @samwata @kahummer - can this be closed?

**Comment by akahure** [comment]
@cKellyDesign most certainly it can be closed!
