### ISSUE TITLE
Add partner icons to show coverage on mouse hover popup 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#442]
In UNOPS Idai we need to change the colours for the coverage for the specific partners. i.e. Once the geographical layer has been activated by selecting a partner, it needs to appear with different subtle colours, to show representation (Not red or green).

Additionally, have an icon to represent the client once a user hovers their mouse on a region. Proposed the following by the client:

UNICEF Education - could use 'books' symbol
UNICEF WASH -  could use 'hand washing' symbol
UNICEF Health - could use 'health care facility' symbol
UNOPS CI - could use 'construction' symbol
FAO -  could use 'cattle/crop' symbol
WFP - could use 'food distribution' symbol
WHO -  could use 'health care facility' symbol bud differentiated from UNICEF health

@ciremusyoka we can commence looking at this implementation while we discuss with @cKellyDesign on what possible icons we can use for this.

**Comment by cKellyDesign** [comment]
@jholmes525 - For icons like this we usually turn to @rowo, these sound similar to those in Mesh2 dashboards though I'm not sure if those were proprietary (to DIFD) but if not we could probably re-use those.

> I'm not sure if those [icons] were proprietary (to DIFD)

cc ^ @engwiri is it ok if we re-use these in the context of Idai?

**Comment by akahure** [comment]
The icons have been added, thanks @cKellyDesign for this. 
client confirmed they are okay, thanks for the quick turn around time.

**Comment by akahure** [comment]
@ciremusyoka I just had a call with the client, they have requested that in place of the icon appearing on the mouse hover, that it should appear on the region/ district where the colour shading. Can we get a screenshot showing this and I can get approval from the client, let me know. Just off a quick glance can we use some of these libraries

1. https://docs.mapbox.com/mapbox-gl-js/example/add-image/
2. https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
3. https://docs.mapbox.com/mapbox-gl-js/example/set-popup/

**Comment by ciremusyoka** [comment]
@akahure This is possible but if we a presenting one icon per region am worried when multiple layers are selected the icons will overlap and most probably one will only be able to see the icon of recent selected layer in regions which have more than one partner operating.

**Comment by ciremusyoka** [comment]
@akahure To achieve this some additional data work will be required too.

**Comment by cKellyDesign** [comment]
@akahure @ciremusyoka what's the status of this?

**Comment by akahure** [comment]
@cKellyDesign pending client review, will check this week and update here
