### ISSUE TITLE
Issue on UNICEF Indonesia pulling Canopy Dashboard 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#444]
There is an issue with how the UNICEF Indonesia Gisida instance is pulling the canopy dashboard. Not sure why this is happening. 
![Screenshot - 2020-03-23T125837 354](https://user-images.githubusercontent.com/43808025/77304896-2ec33d80-6d06-11ea-8a6a-1e995d06c0f2.png)

**Comment by kahummer** [comment]
@akahure sorry i had duplicated the superset component
