### ISSUE TITLE
Updates to UNOPS Idai recovery site 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#447]
Issues reported from client 

- [x] From client: The infographic for each target needs to be revisited as people are shown the same way as households and community assets...we cannot present this like that. There is also a duplication when representing with small people and then lower down with a bar and pi chart.
Implementation Ona - In indicators where we have households and animals, we should change the icons we are using to represent this i.e. Households, community assets, livestock, birds, irrigation schemes 
We can use this library: https://www.unicef.org/argentina/sites/unicef.org.argentina/files/2018-04/2.2%20UNICEF%20GRAPHICS%20MANUAL%20LITE%201.2.pdf
- [x] Please create a separate section for Damages in order to separate Cyclone Path and Flood Damage from the Infra Damages. 
Implementation Ona- remove all damaged sites and have them in their own menu 
![Screenshot - 2020-03-25T100416 108](https://user-images.githubusercontent.com/43808025/77510518-0c552f80-6e80-11ea-93d7-5f9b8d9fb3b2.png)
- [x] The icons representing the TAs should be what you see in the map if they are too big (minimize them). When you do an overlay of the severity of needs and TAs it should show on the map the severity and TA icons.

**Comment by Janemesi** [comment]
@akahure The damaged infrastructure layers have been moved to a different sector named "Damaged Public Infrastructure"
- The partner layers have been changed to symbol layers with each icon marked at the central point of each ward the partner is operating. Once the client approves, the changes will be deployed to production.
