### ISSUE TITLE
Update UGAtlas site with the menu allowing viewing of canopy dashboards 

### ISSUE THREAD

**Issue by akahure** [onaio/gisida#448]
In the UGAtlas site, we are looking to update the menu on the left side with the options to view the Canopy dashboards. The desired view is shown below 

![Screenshot - 2020-04-09T104620 339](https://user-images.githubusercontent.com/43808025/78870790-5f69dd80-7a4f-11ea-88f1-4291511f3d19.png)

if we can achieve the other icon functionality, this would be beneficial i.e. Split view, Client Icon, homepage view. But for now we should target the dashboards integration at minimum. 

The client will be having subsequent meetings with the Ministry of Health and other donors to review the dashboards and the map data. The ideal scenario would be that the data is consolidated on the same platform rather than having two different platforms. 

The objective thus is to have the entire site present only one front for the dashboards and the map data, they will be integrated from https://discover.ona.io/superset/dashboard/244/?preselect_filters=%7B%2211253%22%3A%20%7B%22financial_year%22%3A%20%5B%222018/19%22%5D%7D%7D

Some queries we need to look into i.e. 
- Can this be done 
- If so what is the estimated Level of effort required and tasks 
- Final approval needs to come from Erick/ Dickson before work can commence 

Stage URL: https://stage-ugatlas.onalabs.org/

**Comment by cKellyDesign** [comment]
@akahure Is the data/dashboard public or private? 👀 

If the data/dashboards are set up with the `public` role ([which they are not](https://user-images.githubusercontent.com/4141527/79175928-d5ee3e80-7db3-11ea-8fc8-ab53d480904b.png)) then we should be good to open the Superset Dashboard via an iFrame, without authentication. 🎉 

If the data/dashboard is to be private then we will need to add an custom oAuth2 flow to authenticate the user, which would add a tremendous load. 🏋️‍♂️ 

Then there is the same issue we have been facing, which is that Gisida doesn't currently have any way to tell if the user is logged in. @ciremusyoka can you touch base with @kahummer on the method he and I discussed to try and get around this issue? I think it was still theory but maybe we can rapid prototype it here in UG Atlas? 🤔

**Comment by akahure** [comment]
@cKellyDesign @ciremusyoka anything on a mockup

**Comment by ciremusyoka** [comment]
@akahure we don't have a mockup building something similar to what we usually have except for the menu. 
The toggle button will be added on the existing menu.

**Comment by ciremusyoka** [comment]
@akahure the page should look like this  without the side bar
![alex](https://user-images.githubusercontent.com/26719807/79431699-766e7980-7fd3-11ea-9d4f-53e49d361e92.png)

**Comment by ciremusyoka** [comment]
@akahure @cKellyDesign  below are the pages.

![frame](https://user-images.githubusercontent.com/26719807/79457645-3a4e0f80-7ff9-11ea-90f7-962e817e73fb.png)

![frame2](https://user-images.githubusercontent.com/26719807/79457663-46d26800-7ff9-11ea-823a-33a738e79b25.png)

**Comment by cKellyDesign** [comment]
@ciremusyoka - great work! Just a few nit-picks about the icon from my end:
1. Can we use an icon that uses outline style (like the map explorer icon) rather than the current knockout style? 
2. When viewing the superset iframe, can we change the icon to a map icon to indicate that clicking it will take the user back to the main map?

**Comment by ciremusyoka** [comment]
> @ciremusyoka - great work! Just a few nit-picks about the icon from my end:
> 
> 1. Can we use an icon that uses outline style (like the map explorer icon) rather than the current knockout style?
> 2. When viewing the superset iframe, can we change the icon to a map icon to indicate that clicking it will take the user back to the main map?

@cKellyDesign will make the changes

**Comment by cKellyDesign** [comment]
[As per this thread](https://onaio.slack.com/archives/C6HQ1E8H0/p1586442438047400), we should make sure the icons also have `alt` and `title` tags for screen-readers and browser-native tooltips.

@akahure What should we title this new button? Is it specific to Polio? Or should it be something generic like `Dashboard View`?

**Comment by ciremusyoka** [comment]
> [As per this thread](https://onaio.slack.com/archives/C6HQ1E8H0/p1586442438047400), we should make sure the icons also have `alt` and `title` tags for screen-readers and browser-native tooltips.
> 
> @akahure What should we title this new button? Is it specific to Polio? Or should it be something generic like `Dashboard View`?

@cKellyDesign No it is not specific to polio that is a dashboard i used for testing and will be updated when @akahure  provides the actual dashboard links.

**Comment by cKellyDesign** [comment]
> No it is not specific to polio that is a dashboard i used for testing and will be updated when @akahure provides the actual dashboard links.

Ah ok cool thanks @ciremusyoka! 

@akahure do we have those dashboard links? I'll assign this ticket to you until we get those posted here, unless there's someone else we should be looping in?

**Comment by cKellyDesign** [comment]
@ciremusyoka here are some icons we can use: [icons_white.zip](https://github.com/onaio/gisida/files/4488773/icons_white.zip)

**Comment by cKellyDesign** [comment]
Some notes from a convo w/ @rowo 

The positioning of the icons feels a little strange given their hierarchy (aka - this little icon hiding over on the right navigates to a completely different experience). Because of this it may make more sense for these icons to live between the site title and the first dropdown of layers.

**Comment by cKellyDesign** [comment]
@ciremusyoka please open a pull request on gisida-private between your `canopy-dashboard` branch and whichever branch you branched off of 🙏

**Comment by cKellyDesign** [comment]
@ciremusyoka here are some screens incorporating [Roger's feedback](https://github.com/onaio/gisida/issues/448#issuecomment-614819068) using the icons zipped above, in these screens i'm just dropping the opacity of the icon to 80% but you might try 75%.

![79457645-3a4e0f80-7ff9-11ea-90f7-962e817e73fb](https://user-images.githubusercontent.com/4141527/79502055-ef75cd00-7fe3-11ea-852f-eba54faf878f.png)
![79457663-46d26800-7ff9-11ea-823a-33a738e79b25](https://user-images.githubusercontent.com/4141527/79502088-fbfa2580-7fe3-11ea-8bae-8088862ed19f.png)

**Comment by cKellyDesign** [comment]
As for the Map Explorer button, maybe we could position it `fixed` and make it look like one of the map control buttons (the button lives outside of the React components which is why we can't just migrate it into the gisida-private branch). Though maybe that should be lower priority than getting the iframes working.

**Comment by ciremusyoka** [comment]
@cKellyDesign Adding the two icons at once will make it impossible to achieve responsiveness on smaller screen.
![ug1](https://user-images.githubusercontent.com/26719807/79738867-07ac5b80-8306-11ea-9f13-af9acc564d59.png)

**Comment by ciremusyoka** [comment]
@cKellyDesign Have opted to show the two icons only dashboard page is active
![uga1](https://user-images.githubusercontent.com/26719807/79749695-5236d380-8318-11ea-8335-8e07f9611caa.png)

**Comment by ciremusyoka** [comment]
@akahure Have deployed the changes to [stage](https://stage-ugatlas.onalabs.org/).

**Comment by cKellyDesign** [comment]
> @cKellyDesign Have opted to show the two icons only dashboard page is active

@ciremusyoka why?

**Comment by cKellyDesign** [comment]
@ciremusyoka When we have two icons showing like this, one of them should have their opacity dropped to around `.7` to indicate it's not the active view.

<img width="281" alt="Screen Shot 2020-04-20 at 5 35 30 AM" src="https://user-images.githubusercontent.com/4141527/79752329-fe50ce00-82c8-11ea-81c7-c83235949b67.png">

**Comment by ciremusyoka** [comment]
> > @cKellyDesign Have opted to show the two icons only dashboard page is active
> 
> @ciremusyoka why?

Because of the responsiveness on smaller devices.

**Comment by cKellyDesign** [comment]
> > > @cKellyDesign Have opted to show the two icons only dashboard page is active
> >
> > @ciremusyoka why?
>
> Because of the responsiveness on smaller devices.

Ah ok that makes sense. Maybe then we can just toggle the two icons in the same place (so show the chart icon when on the map and show the map icon when on the dashboard)?

**Comment by ciremusyoka** [comment]
> > > > @cKellyDesign Have opted to show the two icons only dashboard page is active
> > > 
> > > 
> > > @ciremusyoka why?
> > 
> > 
> > Because of the responsiveness on smaller devices.
> 
> Ah ok that makes sense. Maybe then we can just toggle the two icons in the same place (so show the chart icon when on the map and show the map icon when on the dashboard)?

@cKellyDesign This can work too.

**Comment by cKellyDesign** [comment]
@akahure are the Superset dashboards completely set up for this? The dashboard we have in there currently looks to be private.

<img width="1468" alt="Screen Shot 2020-04-21 at 9 30 08 AM" src="https://user-images.githubusercontent.com/4141527/80018663-39026400-848b-11ea-86d1-9d2c07355ffc.png">
