### ISSUE TITLE
Set up a GISIDA site for Hello Mwana based on Idai Recovery Zimbabwe

### ISSUE THREAD

**Issue by msschroeder** [onaio/gisida#451]
Requestor: Megan - UNICEF Zimbabwe - Hello Mwana

Description:
We need to set up a new GISIDA site for this project

* [x] Create a GISIDA site for UNICEF Zimbabwe using the same basemap used in the Idai Zimbabwe Recovery GISIDA Instance (https://github.com/onaio/idai-recovery-zimbabwe)
* [x] Use the domain name: hellomwana-zimbabwe.onalabs.org
* [x] The site needs to be password protected for both embedded canopy and GISIDA map
* [x] It should allow a splash page
* [x] It should allow a Canopy Dashboard to be embedded later

Layers to pull from Idai Zimbabwe Recovery GISIDA instance:

* [x] All the layers from `Boundaries and Labels`
* [x] From `Settlements + Services`, Layers: `Roads`, `Zimbabwe towns`, `Zimbabwe highways`
* [x] From `Demographics`, Layers: `Province population`, `District populations`, `Ward populations`, `Zimbabwe Population (raster)`
* [x] From https://zimbabwe.onalabs.org/, take the layer from `2019 Archived data` > `Health`, Layer: `Weekly Disease Surveillance` (both province and district) - This can be done by the data team member assigned to this work

Dependencies
No dependencies

Priority
7-8

Timeline
Start by April 27th

**Comment by cKellyDesign** [comment]
@msschroeder thanks for the ticket, it all seems pretty straightforward! 

Do we have the `splash page` requirements scoped out? Are we pulling this from [idai-recovery](https://idairecovery-zimbabwe.onalabs.org/) as well or should this be different?

**Comment by cKellyDesign** [comment]
@ukanga currently my estimate for this is 8-16 hours, if customizations are required for the splash page (or elsewhere) I will re-adjust this estimate. 🤗

**Comment by cKellyDesign** [comment]
@msschroeder @akahure do which logo should we be using in the left-hand titlebar?

**Comment by msschroeder** [comment]
@cKellyDesign Please use UNICEF logo from https://zimbabwe.onalabs.org/

**Comment by msschroeder** [comment]
@cKellyDesign Is it possible to update the icon with the following icon? And the accompany side menu color to match something in the icon, shown once you log in?
![mohcc-logo](https://user-images.githubusercontent.com/20777928/80806710-13c8d080-8bc4-11ea-8cb7-986a0cd2c4ee.jpg)

**Comment by msschroeder** [comment]
@cKellyDesign The Icon was kindly updated yesterday by @kelvin-muchiri. However, the side panel was not updated to the correct color. Also, the client raised that they would like the background of the icon on the side menu to match the green. I have gotten Roger to make the background transparent. Can you do the following to update the look and feel:

- [ ] Update the side panel color (#1a632f) and icon (attached -please choose the appropriate size:
![80806710-13c8d080-8bc4-11ea-8cb7-986a0cd2c4ee-smallest](https://user-images.githubusercontent.com/20777928/80995112-66b1ba80-8e46-11ea-8846-5d1033a4df51.png)
![80806710-13c8d080-8bc4-11ea-8cb7-986a0cd2c4ee-large](https://user-images.githubusercontent.com/20777928/80995115-674a5100-8e46-11ea-91ab-976e831f6fee.png)
![80806710-13c8d080-8bc4-11ea-8cb7-986a0cd2c4ee-small](https://user-images.githubusercontent.com/20777928/80995116-67e2e780-8e46-11ea-9ba9-2bdbba55bd58.png)
