### ISSUE TITLE
Unable to see the embedded dashboard - Hello Mwana

### ISSUE THREAD

**Issue by msschroeder** [onaio/gisida#486]
Project - Hello Mwana
Gisida Instance - https://hellomwana-zimbabwe.onalabs.org/

Is the reason the dashboard cannot be viewed related to permissions on Canopy or GISIDA:

To replicate:
1. Log in to https://hellomwana-zimbabwe.onalabs.org/
2. Navigate to Canopy dashboard
3. You are requested to log into Canopy (on a normal browsing window)

**Comment by kahummer** [comment]
Haven't been able to replicate this. I am able to access the dashboard the issue seems to be the data that populates the different charts on the iframe
![Screenshot from 2020-08-18 10-59-41](https://user-images.githubusercontent.com/16018123/90486713-0e2ad280-e142-11ea-8d1a-10519c1131bd.png)

**Comment by kahummer** [comment]
>You are requested to log into Canopy (on a normal browsing window)

@msschroeder please share screenshots so we can see what that looks like

**Comment by msschroeder** [comment]
@kahummer JK I tried in Firefox - and SURPRISE it worked. I am closing the issue.
