### ISSUE TITLE
The side panel menus appear to be repeating themselves on two different accounts

### ISSUE THREAD

**Issue by msschroeder** [onaio/gisida#487]
Project - Hello Mwana
Gisida Instance - https://hellomwana-zimbabwe.onalabs.org/

<img width="1128" alt="Screen Shot 2020-08-17 at 10 28 42 PM" src="https://user-images.githubusercontent.com/20777928/90436276-0aaf3100-e0d9-11ea-9767-eca6d9f8eacd.png">

To replicate:
1. Log in to https://hellomwana-zimbabwe.onalabs.org/
2. Navigate to Nutrition > Health Facility Indicators > Health Facilities > menus repeat as you scroll down
3. You are requested to log into Canopy (on a normal browsing window)

**Comment by kahummer** [comment]
@msschroeder I've added a fix for the menu but there are some issues that came up from some of the layers. I had a look at some and they were data related, will work with @samwata  to get this working fine.
