### ISSUE TITLE
Using Free Highcharts library version for Gisida which is a commercial product

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/gisida#63]
@cKellyDesign @royrutto @engwiri 
According to highchart's terms of use, the free version is only used for non-commercial products like personal websites, school sites e.t.c. This is not the case for Gisida which is now a commercial product. See their documentation https://www.highcharts.com/products/highcharts/

**Comment by cKellyDesign** [comment]
In discussions around Gisida as a Presentation Layer for Canopy @mberg mentioned the possibility of using Ant chart components.
